spring:
  application:
    name: am01-mediavault-apigateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: uploadservice_route
          predicates:
            - Path=/uploadservice/**
          uri: ${uploadservice:http://localhost:8080}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${client-id}
            client-secret: ${client-secret}


server:
  port: 8000

logging:
  level:
    org.springframework.cloud.gateway: WARN
    org.springframework.security: TRACE

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway




